### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by knv** [mikeal/couchdb-pythonviews#2]
Is this project dead?

**Comment by mikeal** [comment]
Nope, it's just working :)

I think benoitc is using it in couchdbkit as well although he may be keeping a local version with modifications.

**Comment by knv** [comment]
Actually I am looking for some general documentation. It seems that it doesn't work the same way that couchdb-python works (for instance the way you set it up).

**Comment by mikeal** [comment]
If you look at tests/view_server.py you can see the script you want to use to enable.

http://github.com/mikeal/couchdb-pythonviews/blob/master/tests/view_server.py
- install the package with setuptools (easy_install or pip)
- copy test/view_server.py and chmod 755
- enable this script as the "python" view server in your couchdb config
